import { lesson, mathReference, englishReference } from './shared';

const math = {
  child: 'xiaobao' as const,
  subject: '数学' as const,
  reference: mathReference,
};
const english = {
  child: 'xiaobao' as const,
  subject: '英语' as const,
  reference: englishReference,
  chapter: '英语基础 · 语境与句子',
};

export const juniorLessons = [
  lesson({
    ...math,
    id: 'xb-number-line',
    week: 1,
    title: '位置和路程，不是同一个数',
    chapter: '有理数基础 · 数轴',
    objective: '分清终点、起终点距离和总路程。',
    hook: '小机器人先前进再后退，计步器不会把后退的步数扣掉。',
    steps: [
      '向右记正、向左记负，先求终点。',
      '起终点距离取坐标差的绝对值。',
      '总路程把每段走的长度相加。',
    ],
    trap: '往返后的位置可能没变，路程却不为0。',
    example: {
      prompt: '从−4向右7，再向左2。',
      steps: [
        '终点：−4＋7−2＝1。',
        '起终点距离：|1−(−4)|＝5。',
        '路程：7＋2＝9。',
      ],
    },
    parentPrompt: '回到原点就等于没走路吗？',
    questions: [
      ['从−3向右5，终点是？', ['−8', '2', '8'], 1, '−3＋5＝2。'],
      ['从4向左7，离原点多远？', ['−3', '11', '3'], 2, '终点−3，距离为3。'],
      ['向右5再向左5，路程是？', ['0', '10', '5'], 1, '路程相加，5＋5＝10。'],
      [
        '从−2向右6再向左1，起终点距离是？',
        ['5', '7', '3'],
        0,
        '终点3；3−(−2)＝5。',
      ],
    ],
  }),
  lesson({
    ...math,
    id: 'xb-subtract-negative',
    week: 2,
    title: '减去一个负数：先改写再算',
    chapter: '有理数基础 · 减法',
    objective: '把减法改成加相反数，而不是见负号就猜。',
    hook: '账本上撤掉一笔欠款，余额反而增加。比喻帮你想，规则帮你算。',
    steps: [
      '保留前面的数。',
      '减号改加号，被减去的整个数取相反数。',
      '按有理数加法计算。',
    ],
    trap: '−2−(−5)中第二个负数的相反数是＋5；第一个−2不能也变号。',
    example: { prompt: '−2−(−5)', steps: ['＝−2＋5。', '＝3。'] },
    parentPrompt: '这一题究竟是哪一个数在取相反数？',
    questions: [
      ['−3−(−8)＝？', ['−11', '5', '−5'], 1, '−3＋8＝5。'],
      ['4−7＝？', ['3', '11', '−3'], 2, '4＋(−7)＝−3。'],
      ['−2−(+5)＝？', ['3', '−7', '7'], 1, '减正5等于加负5，得到−7。'],
      ['−6−(−4)＋3＝？', ['−7', '1', '−13'], 1, '−6＋4＋3＝1。'],
    ],
  }),
  lesson({
    ...math,
    id: 'xb-power',
    week: 3,
    title: '负号在门里，还是门外？',
    chapter: '有理数基础 · 乘方',
    objective: '准确识别乘方的底数。',
    hook: '括号是一扇门：负号进了门，才和数字一起被平方。',
    steps: [
      '圈出底数，别先算。',
      '先算乘方，再处理门外的负号。',
      '比较结果的符号是否符合展开式。',
    ],
    trap: '−3²不是(−3)²；但(−3)³仍是负数。',
    example: {
      prompt: '比较−3²与(−3)²。',
      steps: ['−3²＝−(3×3)＝−9。', '(−3)²＝(−3)×(−3)＝9。'],
    },
    parentPrompt: '把每个乘方展开成乘法，负号在哪里？',
    questions: [
      ['−4²＝？', ['16', '−16', '−8'], 1, '底数是4，外面的负号最后处理。'],
      ['(−4)²＝？', ['−16', '8', '16'], 2, '底数−4，两个负数相乘为正。'],
      ['(−2)³＝？', ['−8', '8', '−6'], 0, '三个−2相乘是−8。'],
      ['−2²＋(−2)²＝？', ['8', '−8', '0'], 2, '−4＋4＝0。'],
    ],
  }),
  lesson({
    ...math,
    id: 'xb-brackets',
    week: 3,
    title: '括号前的负号，要照顾每一项',
    chapter: '整式基础 · 去括号',
    objective: '把去括号理解为分配律。',
    hook: '给盒子里每件商品打折，不能只给第一件打折。括号外的数也要乘到每一项。',
    steps: [
      '把减括号看作乘−1。',
      '外面的数逐项相乘，保留每项的符号。',
      '最后合并同类项。',
    ],
    trap: '−(a−3)＝−a＋3，不是−a−3。',
    example: { prompt: '2a−(a−3)', steps: ['＝2a−a＋3。', '＝a＋3。'] },
    parentPrompt: '负号为什么也会影响括号里的−3？',
    questions: [
      ['−(x−5)＝？', ['−x−5', '−x＋5', 'x＋5'], 1, '−1逐项乘进去。'],
      ['2(x＋3)＝？', ['2x＋3', 'x＋6', '2x＋6'], 2, '2要分别乘x和3。'],
      ['3a−2(a−1)＝？', ['a＋2', 'a−2', '5a−2'], 0, '3a−2a＋2＝a＋2。'],
      ['4x−(2x＋1)＝？', ['2x＋1', '2x−1', '6x＋1'], 1, '4x−2x−1＝2x−1。'],
    ],
  }),
  lesson({
    ...math,
    id: 'xb-like-terms',
    week: 3,
    title: '同类项分拣：看标签，不看盒数',
    chapter: '整式基础 · 合并同类项',
    objective: '按字母与相同字母的指数分类。',
    hook: '苹果和梨分别数。3个苹果和−2个苹果能合并，3个苹果和2个梨不能凑成5个苹果。',
    steps: [
      '先看字母是否相同。',
      '再看相同字母的指数是否相同。',
      '只加减系数，字母与指数不改。',
    ],
    trap: '2a和2a²不是同类项；ab和ba是同类项。',
    example: {
      prompt: '3a＋2b−a',
      steps: ['a类：3a−a＝2a。', 'b类只有2b。', '结果2a＋2b。'],
    },
    parentPrompt: '为什么3a＋2a不是5a²？',
    questions: [
      [
        '哪项与3a²同类？',
        ['−2a²', '3a', '3b²'],
        0,
        '字母a和指数2都相同，系数不必相同。',
      ],
      ['3x＋2x＝？', ['5x²', '6x', '5x'], 2, '只加系数3＋2，指数不变。'],
      [
        '2ab＋3ba＝？',
        ['5ab', '5a²b²', '不能合并'],
        0,
        'ba＝ab，两个字母及其指数相同。',
      ],
      ['5a−2b−3a＋b＝？', ['2a−b', '2a−3b', '8a−b'], 0, 'a类为2a，b类为−b。'],
    ],
  }),
  lesson({
    ...math,
    id: 'xb-substitution',
    week: 4,
    title: '整体代入：不用先把字母都求出来',
    chapter: '整式基础 · 整体思想',
    objective: '识别已知式子与目标式子的倍数关系。',
    hook: '已知一个套餐的价钱，买3份套餐不必先查清每样单品。',
    steps: [
      '圈出已知的整体。',
      '检查目标式子的各项系数是否同倍变化。',
      '用整体替换，再处理剩下的常数。',
    ],
    trap: '系数不是同一倍数时，不能强凑套餐。',
    example: {
      prompt: '2a−b＝3，求6a−3b＋5。',
      steps: ['6a−3b＝3(2a−b)。', '原式＝3×3＋5＝14。'],
    },
    parentPrompt: '这里为何不用分别求a和b？',
    questions: [
      ['2a−b＝3，6a−3b＋5＝？', ['8', '14', '18'], 1, '3(2a−b)＋5＝14。'],
      ['x＋y＝4，2x＋2y＝？', ['6', '16', '8'], 2, '2(x＋y)＝8。'],
      [
        '只知道x＋y＝4，能唯一确定2x＋y吗？',
        ['能，等于8', '不能', '能，等于4'],
        1,
        'x＝0、y＝4和x＝1、y＝3给出不同结果。',
      ],
      ['a−2b＝−3，2a−4b−1＝？', ['−7', '−5', '5'], 0, '2(a−2b)−1＝−6−1＝−7。'],
    ],
  }),
  lesson({
    ...math,
    id: 'xb-equation',
    week: 4,
    title: '列方程：先找一样多的两边',
    chapter: '方程基础 · 等量关系',
    objective: '先用话说等量关系，再把未知数放进去。',
    hook: '天平两边一样重。列方程就是找两种说法表达的同一个量。',
    steps: [
      '说明x代表什么，写单位。',
      '把等量关系写成一句话或表格。',
      '求解后代回原情境检查。',
    ],
    trap: '不能看到数字就全加起来；问价格、人数或长度时，单位要一致。',
    example: {
      prompt: '3本相同本子和1支2元的笔共14元，每本本子多少钱？',
      steps: ['设每本x元。', '3x＋2＝14，3x＝12。', 'x＝4；检查3×4＋2＝14。'],
    },
    parentPrompt: '方程左边和右边分别是什么总量？',
    questions: [
      [
        '4本每本x元的本子和2元笔共18元，方程是？',
        ['4x＋2＝18', '4＋x＋2＝18', '4(x＋2)＝18'],
        0,
        '本子总价4x，再加笔2元。',
      ],
      ['2x＋3＝11，x＝？', ['7', '4', '8'], 1, '2x＝8，所以x＝4。'],
      [
        '长方形长x、宽3，周长18，方程是？',
        ['x＋3＝18', '3x＝18', '2(x＋3)＝18'],
        2,
        '周长是两条长加两条宽。',
      ],
      [
        '5张票每张x元，优惠10元后付40元，x＝？',
        ['6', '10', '8'],
        1,
        '5x−10＝40，5x＝50，所以x＝10。',
      ],
    ],
  }),
  lesson({
    ...math,
    id: 'xb-check',
    week: 4,
    title: '小侦探找错：一组数就能推翻“一定”',
    chapter: '综合复习 · 反例检验',
    objective: '用特值快速检查错误结论，但不把一次验证当证明。',
    hook: '一个反例能拆穿“所有”，一个例子却不能证明“所有”。你来当公式侦探。',
    steps: [
      '先试0、1、−1等简单值，必须符合题目条件。',
      '两边不同就找到反例。',
      '两边相同只能说明这个例子通过，还要用规律证明一般情况。',
    ],
    trap: '取a＝1发现|a|＝a，不能证明所有a都成立。',
    example: {
      prompt: '“|a|＝a对所有a成立”对吗？',
      steps: [
        '取a＝−1。',
        '左边1，右边−1，不相等。',
        '所以原说法错误，正确条件是a≥0。',
      ],
    },
    parentPrompt: '验证一次和证明所有情况，有什么区别？',
    questions: [
      [
        '哪个数能反驳“|a|＝a总成立”？',
        ['1', '−1', '0'],
        1,
        'a＝−1时两边不同。',
      ],
      [
        'a＝2时a＋a＝a²成立，能证明恒成立吗？',
        ['能', '不能', '只有正数都成立'],
        1,
        'a＝1时2不等于1。',
      ],
      [
        '化简式只在x<0时有效，哪个值可用于检查？',
        ['2', '0', '−2'],
        2,
        '必须先满足x<0。',
      ],
      [
        '哪种做法最完整？',
        [
          '试一个数就说证明了',
          '找到反例说明原说法不总成立',
          '只看答案是否好看',
        ],
        1,
        '反例可否定全称命题，验证单个例子不能证明全称命题。',
      ],
    ],
  }),
  lesson({
    ...english,
    id: 'xb-english-be',
    week: 1,
    title: '句子找队长：be还是实义动词',
    objective: '区分状态与动作，避免重复谓语。',
    hook: '一句话先找“谁”和“怎么样/做什么”。I am happy是状态，I play是动作。',
    steps: [
      '找主语。',
      '表示身份、状态时看be；描述一般习惯动作时看实义动词。',
      '本课的一般现在时动作句不额外加am/is/are。',
    ],
    trap: 'I am play football every day不对；正在进行的动作另有am playing等结构。',
    example: {
      prompt: 'She ___ a student. She ___ books every day.',
      steps: ['身份：She is a student。', '习惯：She reads books every day。'],
    },
    parentPrompt: '这句话是在讲身份，还是在讲一个习惯动作？',
    questions: [
      ['I ___ a student.', ['am', 'is', 'are'], 0, 'I搭配am。'],
      ['They ___ happy.', ['am', 'is', 'are'], 2, 'They搭配are。'],
      [
        '哪句正确表达“我每天踢足球”？',
        [
          'I am play football every day.',
          'I play football every day.',
          'I is play football every day.',
        ],
        1,
        '一般现在时实义动词play前不加be。',
      ],
      [
        'She ___ my friend.',
        ['are', 'am', 'is'],
        2,
        'She是第三人称单数，be用is。',
      ],
    ],
  }),
  lesson({
    ...english,
    id: 'xb-english-third',
    week: 2,
    title: '找准主语，再给动词换衣服',
    objective: '判断第三人称单数并正确变形。',
    hook: '动词穿什么衣服，先看主语是谁；别只盯括号里的单词。',
    steps: [
      '确认表达现在的习惯。',
      '主语为he/she/it或单数人/物时，肯定句实义动词通常变第三人称单数。',
      'watch加es；study辅音字母＋y结尾变studies。',
    ],
    trap: 'Lily and Tom是两个人，不用单数形式；有do/does的句子另检查原形。',
    example: {
      prompt: 'Lucy ___ (watch) TV after dinner every day.',
      steps: ['Lucy是第三人称单数。', 'watch以ch结尾，加es，得到watches。'],
    },
    parentPrompt: '把Lucy换成Lucy and Tom，动词怎样变？',
    questions: [
      [
        'Lucy ___ TV every evening.',
        ['watch', 'watches', 'watching'],
        1,
        'Lucy为第三人称单数，肯定句用watches。',
      ],
      [
        'My brother ___ English every day.',
        ['study', 'studys', 'studies'],
        2,
        'study变y为i再加es。',
      ],
      [
        'Lily and Tom ___ to school every day.',
        ['walk', 'walks', 'walking'],
        0,
        '复数主语，实义动词用原形。',
      ],
      [
        'He ___ football on Sundays.',
        ['play', 'plays', 'playing'],
        1,
        '第三人称单数肯定句用plays。',
      ],
    ],
  }),
  lesson({
    ...english,
    id: 'xb-english-do',
    week: 3,
    title: 'does上场，动词恢复原形',
    objective: '把一般现在时实义动词句改为问句、否定句。',
    hook: 'does已经替句子穿上单数衣服，后面的动词就不用再穿一次。',
    steps: [
      '先认主语单复数。',
      '第三人称单数用does/doesn’t；其他用do/don’t。',
      '后面实义动词恢复原形。',
    ],
    trap: 'Does she reads…不对；be动词句不能直接套这个模板。',
    example: {
      prompt: 'Lily reads books every day. 改疑问句。',
      steps: [
        '主语Lily，选Does。',
        'reads改read。',
        'Does Lily read books every day?',
      ],
    },
    parentPrompt: '为什么does和reads不能在这里同时表示单数？',
    questions: [
      [
        '___ Lily read books every day?',
        ['Do', 'Does', 'Is'],
        1,
        '单数主语的实义动词问句用Does。',
      ],
      [
        'She doesn’t ___ football.',
        ['plays', 'playing', 'play'],
        2,
        'doesn’t后接动词原形。',
      ],
      [
        '___ Lily and Tom walk to school?',
        ['Do', 'Does', 'Is'],
        0,
        '复数主语用Do。',
      ],
      [
        '哪句正确？',
        [
          'Does he studies English?',
          'Does he study English?',
          'Do he studies English?',
        ],
        1,
        'Does配he，study恢复原形。',
      ],
    ],
  }),
  lesson({
    ...english,
    id: 'xb-english-evidence',
    week: 4,
    title: '阅读小侦探：答案要带证据',
    objective: '根据问法定位信息，留意否定和条件。',
    hook: '选项里出现原文单词，不代表它就是答案。每个答案都要带着证据回来。',
    steps: [
      '先看问谁、何时、哪里、为什么或怎样。',
      '找到对应句，圈出否定词、时间与条件。',
      '用句子回答，再核对是否回答了原问题。',
    ],
    trap: '不要只匹配重复单词，尤其留意not、but和when引出的条件。',
    example: {
      prompt:
        'Lily walks to school on sunny days. When it rains, she takes the bus. How does she go on rainy days?',
      steps: [
        '问雨天的方式，不是晴天。',
        '证据是When it rains后半句。',
        'She takes the bus.',
      ],
    },
    parentPrompt: '如果删掉when it rains，问题还一样吗？',
    questions: [
      [
        'Tom likes science, but he doesn’t like history. 他不喜欢什么？',
        ['Science', 'History', 'Both'],
        1,
        'doesn’t like history是否定信息。',
      ],
      [
        'The club starts at four, not five. 何时开始？',
        ['At five', 'At six', 'At four'],
        2,
        'not five排除五点。',
      ],
      [
        'Ann reads in the library after lunch. Where does she read?',
        ['In the library', 'After lunch', 'Ann'],
        0,
        'Where问地点，不是时间。',
      ],
      [
        'Ben usually walks, but today he takes a bus. How does he travel today?',
        ['On foot', 'By bus', 'By bike'],
        1,
        'today对应后半句，不能只看usually。',
      ],
    ],
  }),
];
