#!/usr/bin/env python3
"""Publish a verified APK from this project's private archive; run on Tencent as root.

Only explicitly named APKs and sanitized release JSON are exposed. TLS checks use
the system trust store. Existing application release and private data are untouched.
"""
import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from uuid import uuid4

PROJECT = Path('/home/ubuntu/codex_project/workspace_own/family-learning-hub')
PUBLIC = PROJECT / 'artifacts/public/android'
MOUNT = Path('/var/www/familylearningapk')
UNIT = 'var-www-familylearningapk.mount'
ORIGIN = 'https://123.207.232.151'
URL_ROOT = ORIGIN + '/family-learning/downloads/android/'
CONFIG = PROJECT / 'config/nginx/family-learning-apk-downloads.conf'
INCLUDE = Path('/etc/nginx/snippets/family-learning-apk-downloads.conf')
FAMILY_CONFIG = PROJECT / 'config/nginx/family-learning-location.conf'
REGISTRY = PROJECT / 'config/apk-releases.json'
UNIT_CONFIG = PROJECT / 'config/systemd' / UNIT
UNIT_LINK = Path('/etc/systemd/system') / UNIT


def run(*args):
    return subprocess.run([str(a) for a in args], check=True, capture_output=True, text=True).stdout.strip()


def sha(data):
    return hashlib.sha256(data).hexdigest()


def is_mounted():
    # os.path.ismount cannot reliably detect same-filesystem bind mounts.
    return subprocess.run(['findmnt', '-n', '--mountpoint', str(MOUNT)],
                          capture_output=True).returncode == 0


def inside_project(path):
    if not path.resolve().is_relative_to(PROJECT.resolve()):
        raise RuntimeError('Path is outside this project: ' + str(path))


def atomic(path, data, mode=0o600):
    inside_project(path)
    temp = path.with_name(path.name + '.pending-' + uuid4().hex)
    try:
        with temp.open('xb') as f:
            f.write(data)
            f.flush()
            os.fsync(f.fileno())
        temp.chmod(mode)
        temp.replace(path)
    finally:
        temp.unlink(missing_ok=True)


def json_bytes(value):
    return (json.dumps(value, ensure_ascii=False, indent=2) + '\n').encode()


def immutable(path, data):
    if path.exists() or path.is_symlink():
        if path.is_symlink() or not path.is_file() or sha(path.read_bytes()) != sha(data):
            raise RuntimeError('Refusing to replace an immutable release: ' + path.name)
    else:
        atomic(path, data, 0o644)


def download(url, expected_sha, expected_size):
    digest, size = hashlib.sha256(), 0
    # Default urllib TLS verification is intentional; no unverified SSL context.
    with urllib.request.urlopen(url, timeout=45) as response:
        assert response.status == 200 and response.geturl().startswith(URL_ROOT)
        assert response.headers.get_content_type() == 'application/vnd.android.package-archive'
        assert 'attachment' in response.headers.get('Content-Disposition', '')
        for chunk in iter(lambda: response.read(256 * 1024), b''):
            size += len(chunk)
            if size > expected_size:
                raise RuntimeError('Download exceeds the expected size')
            digest.update(chunk)
        final_url = response.geturl()
    assert size == expected_size and digest.hexdigest() == expected_sha
    return dict(url=url, final_url=final_url, bytes=size, sha256=digest.hexdigest(), tls_verified=True)


def denied(url):
    try:
        with urllib.request.urlopen(url, timeout=20) as response:
            raise RuntimeError('Unexpected public response for private path: ' + str(response.status))
    except urllib.error.HTTPError as error:
        assert error.code in (400, 403, 404), (url, error.code)
        return dict(url=url, status=error.code)


def nginx_config(entries, latest):
    blocks = ['# Generated by scripts/publish-apk.py. Only exact release filenames are public.']
    for entry in entries:
        for name, mime, disposition in [
            (entry['fileName'], 'application/vnd.android.package-archive', True),
            (entry['fileName'][:-4] + '.json', 'application/json', False),
        ]:
            lines = [f'location = /family-learning/downloads/android/{name} {{',
                     f'    alias {MOUNT}/{name};', '    types { }', f'    default_type {mime};',
                     '    disable_symlinks on;', '    autoindex off;',
                     '    limit_except GET { deny all; }',
                     '    add_header X-Content-Type-Options nosniff always;',
                     '    add_header Cache-Control "public, max-age=31536000, immutable" always;']
            if disposition:
                lines.append(f'    add_header Content-Disposition \'attachment; filename="{name}"\' always;')
            lines.append('}')
            blocks.append('\n'.join(lines))
    blocks.extend([
        'location = /family-learning/downloads/android/latest.apk {\n'
        '    add_header Cache-Control "no-store" always;\n'
        f'    return 302 {latest["downloadUrl"]};\n}}',
        'location = /family-learning/downloads/android/latest.json {\n'
        f'    alias {MOUNT}/latest.json;\n'
        '    types { }\n    default_type application/json;\n    disable_symlinks on;\n'
        '    set $family_apk_cors_origin "";\n'
        '    if ($http_origin = "https://localhost") { set $family_apk_cors_origin "https://localhost"; }\n'
        '    if ($request_method = OPTIONS) { return 204; }\n'
        '    limit_except GET OPTIONS { deny all; }\n'
        '    add_header Access-Control-Allow-Origin $family_apk_cors_origin always;\n'
        '    add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;\n'
        '    add_header Access-Control-Allow-Headers "Content-Type" always;\n'
        '    add_header Vary "Origin" always;\n'
        '    add_header X-Content-Type-Options nosniff always;\n'
        '    add_header Cache-Control "no-store" always;\n}',
        'location ^~ /family-learning/downloads/ { return 404; }',
    ])
    return ('\n\n'.join(blocks) + '\n').encode()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', required=True, type=Path)
    parser.add_argument('--version', required=True)
    parser.add_argument('--version-code', required=True, type=int)
    parser.add_argument('--changelog', required=True, help='Short public Chinese update summary')
    parser.add_argument('--commit', required=True)
    parser.add_argument('--sha256', required=True)
    parser.add_argument('--bytes', required=True, type=int)
    parser.add_argument('--channel', choices=['debug', 'release'], default='debug')
    parser.add_argument('--notes', required=True, help='Public, non-sensitive release notes')
    args = parser.parse_args()
    assert os.geteuid() == 0, 'Run on the Tencent host with sudo'
    os.umask(0o077)
    assert re.fullmatch(r'[0-9]+(?:\.[0-9]+){1,3}', args.version)
    assert 1 <= args.version_code <= 2100000000 and 0 < len(args.changelog) <= 300
    assert re.fullmatch(r'[a-f0-9]{40}', args.commit)
    assert re.fullmatch(r'[A-Fa-f0-9]{64}', args.sha256)
    assert 0 < args.bytes < 1024 * 1024 * 1024 and len(args.notes) <= 1000
    source = args.source.resolve()
    assert source.is_relative_to(PROJECT / 'artifacts/android') and source.is_file() and source.suffix == '.apk'
    archive = json.loads((source.parent / 'manifest.json').read_bytes())
    assert archive['versionCode'] == args.version_code and archive['commit'] == args.commit
    content = source.read_bytes()
    assert len(content) == args.bytes and sha(content) == args.sha256.lower()
    name = f'family-learning-{args.version}-{args.channel}-{args.commit[:7]}.apk'
    assert FAMILY_CONFIG.is_file() and not FAMILY_CONFIG.is_symlink()
    assert PROJECT.resolve() == PROJECT
    before_release = os.readlink(PROJECT / 'runtime/current')
    before_pid = run('systemctl', 'show', 'family-learning-hub', '-p', 'MainPID', '--value')
    run('nginx', '-t')
    with urllib.request.urlopen(ORIGIN + '/family-learning/', timeout=20) as r:
        assert r.status == 200
    for path in [PUBLIC, CONFIG, REGISTRY, UNIT_CONFIG]:
        inside_project(path)
    for link, target in [(INCLUDE, CONFIG), (UNIT_LINK, UNIT_CONFIG)]:
        assert not os.path.lexists(link) or link.is_symlink() and link.resolve() == target, str(link)
    if MOUNT.exists():
        assert not MOUNT.is_symlink()
        if not is_mounted():
            assert not list(MOUNT.iterdir()), 'Do not hide existing files under a mount'

    tag = datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ') + '-' + uuid4().hex[:6]
    snapshot = PROJECT / 'backups/releases' / ('apk-publish-' + tag)
    snapshot.mkdir(mode=0o700)
    original = {}
    for key, path in [('family.conf', FAMILY_CONFIG), ('downloads.conf', CONFIG), ('registry.json', REGISTRY), ('mount.unit', UNIT_CONFIG), ('latest.json', PUBLIC / 'latest.json')]:
        original[key] = path.read_bytes() if path.is_file() else None
        if original[key] is not None:
            (snapshot / key).write_bytes(original[key])
    registry = json.loads(original['registry.json']) if original['registry.json'] else {'version': 1, 'releases': []}
    entries = registry['releases']
    previous_latest = registry.get('latestMetadata', {})
    if previous_latest:
        assert args.version_code >= previous_latest['versionCode'], 'Refusing a version-code downgrade'
        if args.version_code == previous_latest['versionCode']:
            assert name == previous_latest['fileName'], 'A different APK needs a higher version code'
    existing = next((x for x in entries if x['fileName'] == name), None)
    if existing:
        assert existing['sha256'] == sha(content) and existing['bytes'] == len(content)
        assert existing.get('versionCode', args.version_code) == args.version_code
        public = existing
    else:
        public = dict(app='一起学', version=args.version, channel=args.channel, commit=args.commit,
                      publishedAt=datetime.now(timezone.utc).isoformat(), fileName=name,
                      downloadUrl=URL_ROOT + name, bytes=len(content), sha256=sha(content), notes=args.notes,
                      versionCode=args.version_code, changelog=args.changelog)
        # A failed publish may leave verified immutable files for the next retry.
        staged_metadata = PUBLIC / (name[:-4] + '.json')
        if staged_metadata.exists():
            assert not staged_metadata.is_symlink()
            staged = json.loads(staged_metadata.read_bytes())
            assert set(staged) == set(public)
            assert all(staged[k] == v for k, v in public.items() if k != 'publishedAt')
            datetime.fromisoformat(staged['publishedAt'])
            public = staged
        entries.append(public)
    # Old immutable JSON stays byte-for-byte unchanged; latest adds the update
    # contract for existing releases as well as all future publications.
    latest_public = {**public, 'versionCode': args.version_code, 'changelog': args.changelog}
    mount_was_active = is_mounted()
    link_existed = {str(link): os.path.lexists(link) for link in (INCLUDE, UNIT_LINK)}
    unit_existed = UNIT_CONFIG.exists()
    try:
        PUBLIC.parent.mkdir(mode=0o700, exist_ok=True)
        PUBLIC.mkdir(mode=0o755, exist_ok=True)
        PUBLIC.chmod(0o755)
        immutable(PUBLIC / name, content)
        immutable(PUBLIC / (name[:-4] + '.json'), json_bytes(public))
        if not (PUBLIC / 'latest.json').exists():
            atomic(PUBLIC / 'latest.json', json_bytes(latest_public), 0o644)
        MOUNT.mkdir(mode=0o755, exist_ok=True)
        unit = f'''[Unit]
Description=Read-only Family Learning Hub public APK files
RequiresMountsFor={PUBLIC}
Before=nginx.service

[Mount]
What={PUBLIC}
Where={MOUNT}
Type=none
Options=bind,ro,nosuid,nodev,noexec
DirectoryMode=0755

[Install]
WantedBy=multi-user.target
'''
        atomic(UNIT_CONFIG, unit.encode(), 0o644)
        if not UNIT_LINK.is_symlink():
            UNIT_LINK.symlink_to(UNIT_CONFIG)
        run('systemctl', 'daemon-reload')
        run('systemctl', 'enable', '--now', UNIT)
        assert is_mounted()
        assert (PUBLIC.stat().st_dev, PUBLIC.stat().st_ino) == (MOUNT.stat().st_dev, MOUNT.stat().st_ino)
        options = run('findmnt', '-n', '-o', 'OPTIONS', '--mountpoint', MOUNT).split(',')
        assert all(flag in options for flag in ['ro', 'nodev', 'nosuid', 'noexec'])
        assert run('runuser', '-u', 'www-data', '--', 'sha256sum', MOUNT / name).split()[0] == sha(content)
        atomic(CONFIG, nginx_config(entries, public), 0o644)
        if not INCLUDE.is_symlink():
            INCLUDE.symlink_to(CONFIG)
        include_line = f'include {INCLUDE};'
        family = original['family.conf'].decode()
        if include_line not in family.splitlines():
            atomic(FAMILY_CONFIG, (family.rstrip() + '\n\n# Dedicated public APK download routes.\n' + include_line + '\n').encode(), 0o644)
        run('nginx', '-t')
        run('systemctl', 'reload', 'nginx')
        # Reload signals the master asynchronously; wait for new workers to serve.
        for attempt in range(10):
            try:
                with urllib.request.urlopen(urllib.request.Request(public['downloadUrl'], method='HEAD'), timeout=10) as response:
                    assert response.status == 200
                break
            except urllib.error.HTTPError as error:
                if error.code not in (404, 502, 503) or attempt == 9:
                    raise
                time.sleep(0.5)
        downloads = [download(public['downloadUrl'], sha(content), len(content)), download(URL_ROOT + 'latest.apk', sha(content), len(content))]
        assert all(d['final_url'] == public['downloadUrl'] for d in downloads)
        atomic(PUBLIC / 'latest.json', json_bytes(latest_public), 0o644)
        for origin in ('https://localhost', 'https://untrusted.example'):
            request = urllib.request.Request(URL_ROOT + 'latest.json', headers={'Origin': origin})
            with urllib.request.urlopen(request, timeout=20) as response:
                assert json.load(response) == latest_public
                expected_origin = 'https://localhost' if origin == 'https://localhost' else None
                assert response.headers.get('Access-Control-Allow-Origin') == expected_origin
                assert 'Origin' in response.headers.get('Vary', '')
                assert 'no-store' in response.headers.get('Cache-Control', '')
        request = urllib.request.Request(URL_ROOT + 'latest.json', method='OPTIONS', headers={'Origin':'https://localhost','Access-Control-Request-Method':'GET','Access-Control-Request-Headers':'Content-Type'})
        with urllib.request.urlopen(request, timeout=20) as response:
            assert response.status == 204 and response.headers.get('Access-Control-Allow-Origin') == 'https://localhost'
        request = urllib.request.Request(public['downloadUrl'], headers={'Range': 'bytes=0-1023'})
        with urllib.request.urlopen(request, timeout=20) as response:
            assert response.status == 206 and response.read() == content[:1024]
        blocked = [denied(URL_ROOT + suffix) for suffix in ['', 'manifest.json', 'family-learning-integrated-20261001.bundle', 'apk-verification.json', 'integration-result.json', '.env', '../config/family-learning-sync.env']]
        blocked.append(denied(ORIGIN + '/family-learning/artifacts/android/20261001-2950f3c/family-learning-integrated-20261001.bundle'))
        assert os.readlink(PROJECT / 'runtime/current') == before_release
        assert run('systemctl', 'show', 'family-learning-hub', '-p', 'MainPID', '--value') == before_pid
        assert run('systemctl', 'is-active', 'family-learning-hub') == 'active'
        assert run('systemctl', 'is-active', 'family-learning-backup.timer') == 'active'
        with urllib.request.urlopen(ORIGIN + '/family-learning/', timeout=20) as response:
            assert response.status == 200
        registry['latest'] = name
        registry['latestMetadata'] = latest_public
        atomic(REGISTRY, json_bytes(registry))
        proof = dict(status='published', release=latest_public, downloads=downloads, private_paths=blocked,
                     update_cors='exact https://localhost; GET/HEAD/OPTIONS',
                     readonly_mount=str(MOUNT), physical_directory=str(PUBLIC), snapshot=str(snapshot),
                     production_release_unchanged=before_release, production_pid_unchanged=before_pid,
                     verified_at=datetime.now(timezone.utc).isoformat())
        atomic(snapshot / 'verification.json', json_bytes(proof))
        atomic(PROJECT / 'temp/development/apk-publish-latest.json', json_bytes(proof), 0o640)
        print(json.dumps(dict(status='published', version=args.version, channel=args.channel,
                              version_code=args.version_code,
                              immutable_url=public['downloadUrl'], latest_url=URL_ROOT + 'latest.apk',
                              metadata_url=URL_ROOT + 'latest.json', sha256=sha(content), bytes=len(content),
                              private_paths_blocked=len(blocked), website='unchanged and healthy'), indent=2))
    except Exception:
        # Restore config and pointers; immutable APK copies remain for inspection.
        for key, path in [('family.conf', FAMILY_CONFIG), ('downloads.conf', CONFIG), ('registry.json', REGISTRY), ('latest.json', PUBLIC / 'latest.json')]:
            if original[key] is None:
                path.unlink(missing_ok=True)
            else:
                atomic(path, original[key], 0o600 if key == 'registry.json' else 0o644)
        for link in (INCLUDE,):
            if not link_existed[str(link)] and link.is_symlink():
                link.unlink()
        run('nginx', '-t')
        run('systemctl', 'reload', 'nginx')
        if not mount_was_active:
            subprocess.run(['systemctl', 'disable', '--now', UNIT], capture_output=True)
        if not link_existed[str(UNIT_LINK)] and UNIT_LINK.is_symlink():
            UNIT_LINK.unlink()
        if not unit_existed:
            UNIT_CONFIG.unlink(missing_ok=True)
        else:
            atomic(UNIT_CONFIG, original['mount.unit'], 0o644)
        run('systemctl', 'daemon-reload')
        raise


if __name__ == '__main__':
    main()
