// Generated by scripts/build-launcher-icons.mjs.
import { useId } from 'react';

export function BrandMark({ size = 38 }: { size?: number }) {
  const id = useId();
  return (
    <svg className="brand-mark" width={size} height={size} viewBox="18 18 72 72" aria-hidden="true" focusable="false">
      <defs><linearGradient id={`${id}-background`} gradientUnits="userSpaceOnUse" x1="0" y1="0" x2="108" y2="108"><stop stopColor="#142452"/><stop offset="1" stopColor="#35246D"/></linearGradient><linearGradient id={`${id}-left`} gradientUnits="userSpaceOnUse" x1="38" y1="34" x2="52" y2="70"><stop stopColor="#F1FFFD"/><stop offset="1" stopColor="#66E9F5"/></linearGradient><linearGradient id={`${id}-right`} gradientUnits="userSpaceOnUse" x1="52" y1="30" x2="77" y2="70"><stop stopColor="#A9A4FF"/><stop offset="1" stopColor="#6860EB"/></linearGradient><linearGradient id={`${id}-base`} gradientUnits="userSpaceOnUse" x1="31" y1="67" x2="75" y2="70"><stop stopColor="#32BDF3"/><stop offset="1" stopColor="#A582FF"/></linearGradient><clipPath id={`${id}-clip`}><rect x="18" y="18" width="72" height="72" rx="17"/></clipPath></defs>
      <g clipPath={`url(#${id}-clip)`}>
        <rect width="108" height="108" fill={`url(#${id}-background)`}/>
        <path d="M23,55 L37,55" fill="none" stroke="#E9FAFF" strokeWidth="3.8" strokeLinecap="round" strokeLinejoin="round"/><path d="M63,48 L79,40" fill="none" stroke="#64E9D4" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/><path d="M67,55 L83,55" fill="none" stroke="#69CFFF" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/><path d="M72,65 L79,70" fill="none" stroke="#C19BFF" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/><path d="M52,28 Q53,28 54,30 L76,68 Q77,70 74,70 L30,70 Q27,70 29,67 L50,30 Q51,28 52,28 Z" fill={`url(#${id}-left)`}/><path d="M52,28 Q53,28 54,30 L76,68 Q77,70 74,70 L52,55 Z" fill={`url(#${id}-right)`}/><path d="M29,68 L52,55 L76,69 Q76,70 74,70 L30,70 Q28,70 29,68 Z" fill={`url(#${id}-base)`}/><path d="M52,30 L52,55 L31,68" fill="none" stroke="#F2FFFF" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round" opacity="0.68"/>
      </g>
    </svg>
  );
}
