// Generated by scripts/build-launcher-icons.mjs.
import { useId } from 'react';

export function BrandMark({ size = 38 }: { size?: number }) {
  const id = useId();
  return (
    <svg className="brand-mark" width={size} height={size} viewBox="18 18 72 72" aria-hidden="true" focusable="false">
      <defs><linearGradient id={`${id}-background`} x1="0" y1="0" x2="1" y2="1"><stop offset="0" stopColor="#242850"/><stop offset="1" stopColor="#141831"/></linearGradient><linearGradient id={`${id}-left`} x1="0" y1="0" x2="1" y2="1"><stop offset="0" stopColor="#F0FFFA"/><stop offset="1" stopColor="#5DE5D6"/></linearGradient><linearGradient id={`${id}-right`} x1="0" y1="0" x2="1" y2="1"><stop offset="0" stopColor="#BEACFF"/><stop offset="1" stopColor="#7264DC"/></linearGradient><linearGradient id={`${id}-base`} x1="0" y1="0" x2="1" y2="1"><stop offset="0" stopColor="#67BDFC"/><stop offset="1" stopColor="#B59CF7"/></linearGradient><clipPath id={`${id}-clip`}><rect x="18" y="18" width="72" height="72" rx="17"/></clipPath></defs>
      <g clipPath={`url(#${id}-clip)`}>
        <rect width="108" height="108" fill={`url(#${id}-background)`}/>
        <path d="M53,27 Q54,26 55,28 L80,73 Q81,75 78,75 H29 Q26,75 28,72 Z" fill={`url(#${id}-left)`}/><path d="M54,27 L54,57 L80,74 Q81,75 78,75 Z" fill={`url(#${id}-right)`}/><path d="M28,74 L54,57 L80,74 Q81,75 78,75 H29 Z" fill={`url(#${id}-base)`}/><path d="M54,28 L54,57 L29,74 M54,57 L79,74" fill="none" stroke="#FBFFFF" strokeWidth="0.9" strokeLinecap="round" strokeLinejoin="round" strokeOpacity="0.68"/>
      </g>
    </svg>
  );
}
